#!/usr/bin/env bash
# Start the proxy on its own (context-proxy, port 8096).
#
# The proxy forwards to PROXY_UPSTREAM_URL (independent of the memory group's MEMORY_LLM_*).
# The proxy calls memory:8420 for auth / skill / tdai memory injection, and memory-hub:8125
# for the sessionInit control plane. The proxy can run alone, but those features degrade or switch off.
#
# Usage:
#   ./start-proxy.sh
#
# Needs these proxy settings (in .env):
#   PROXY_UPSTREAM_URL / PROXY_UPSTREAM_API_KEY / PROXY_UPSTREAM_MODEL

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=./_lib.sh
source "$SCRIPT_DIR/_lib.sh"

load_env
require_vars \
  PROXY_IMAGE PROXY_PORT \
  PROXY_UPSTREAM_URL PROXY_UPSTREAM_API_KEY PROXY_UPSTREAM_MODEL

# Same internal gateway credential as memory-core (default local, local use only)
MEMORY_CORE_GATEWAY_API_KEY="${MEMORY_CORE_GATEWAY_API_KEY:-local}"

CONTAINER=tdai-proxy
NETWORK=tdai-memory-stack

if ! $DOCKER network inspect "$NETWORK" >/dev/null 2>&1; then
  info "Creating docker network $NETWORK"
  $DOCKER network create "$NETWORK" >/dev/null
fi

# Dependency check (warns only, doesn't block)
if ! $DOCKER ps --format '{{.Names}}' 2>/dev/null | grep -qx "tdai-memory-core"; then
  warn "The memory-core container is not running; the proxy's auth / tdai memory / skill injection will all degrade."
fi
if ! $DOCKER ps --format '{{.Names}}' 2>/dev/null | grep -qx "tdai-memory-hub"; then
  warn "The memory-hub container is not running; the proxy's sessionInit control plane is unreachable."
fi

pull_image "$PROXY_IMAGE"
rm_container_if_exists "$CONTAINER"

# The proxy reads the upstream URL / API key only from YAML (it ignores a PROXY_UPSTREAM_URL env var),
# so generate a minimal config.yaml from .env and mount it at /data/config.yaml in the container.
# The container CMD is already [--config /data/config.yaml].
CONFIG_DIR="${PROXY_CONFIG_DIR:-$SCRIPT_DIR/.proxy-config}"
mkdir -p "$CONFIG_DIR"
CONFIG_FILE="$CONFIG_DIR/config.yaml"

# ── The three capability switches (minimal by default; dependencies are switched on automatically) ──
# PROXY_ENABLE_AUTH        : clients authenticate with x-tdai-user-key via kernel auth/verify → user_id
# PROXY_ENABLE_SESSION_INIT: form on the first turn to choose team/agent/task; needs auth + tdai
# PROXY_ENABLE_TDAI        : L2/L3 memory injection + L1 recall; needs memory-core
#
# Shortcut: PROXY_FULL_STACK=1 turns all three on.
if [[ "${PROXY_FULL_STACK:-0}" == "1" ]]; then
  PROXY_ENABLE_AUTH=1
  PROXY_ENABLE_TDAI=1
  PROXY_ENABLE_SESSION_INIT=1
fi
PROXY_ENABLE_AUTH="${PROXY_ENABLE_AUTH:-0}"
PROXY_ENABLE_TDAI="${PROXY_ENABLE_TDAI:-0}"
PROXY_ENABLE_SESSION_INIT="${PROXY_ENABLE_SESSION_INIT:-0}"

# sessionInit needs auth to get user_id; turning sessionInit on also turns auth on
if [[ "$PROXY_ENABLE_SESSION_INIT" == "1" && "$PROXY_ENABLE_AUTH" != "1" ]]; then
  warn "PROXY_ENABLE_SESSION_INIT=1 needs auth; turning on PROXY_ENABLE_AUTH"
  PROXY_ENABLE_AUTH=1
fi

bool() { [[ "$1" == "1" ]] && echo "true" || echo "false"; }

info "Generating proxy config → $CONFIG_FILE  (auth=$(bool $PROXY_ENABLE_AUTH) session-init=$(bool $PROXY_ENABLE_SESSION_INIT) tdai=$(bool $PROXY_ENABLE_TDAI))"
cat > "$CONFIG_FILE" <<YAML
# Generated by start-proxy.sh — overwritten on every start, don't edit by hand.
server:
  host: 0.0.0.0
  port: 8096
  forwardTimeoutMs: 600000

upstream:
  url: "${PROXY_UPSTREAM_URL}"
  apiKey: "${PROXY_UPSTREAM_API_KEY}"

log:
  file: ""
  level: info
  backend: console

# tdai kernel connection (for injection / skill / auth)
tdai:
  enabled: $(bool $PROXY_ENABLE_TDAI)
  endpoint: "http://memory-core:8420"
  apiKey: "${MEMORY_CORE_GATEWAY_API_KEY}"
  serviceId: default
  memory:
    enabled: true
    inject: true
    writeL0: true
    recallL1: true
    injectL2L3: true

skill:
  endpoint: "http://memory-core:8420"
  # core's /v3/skill/* requires a non-empty Bearer; with the Bearer gate off the value isn't checked, so use a placeholder
  serviceToken: "${MEMORY_CORE_GATEWAY_API_KEY:-local}"

# Registration threshold for the knowledge injector (shouldRegisterKnowledgeInjector):
# injectors must include knowledge, and knowledge.enabled + knowledge.serviceToken must both be set.
# Without this section the injector silently doesn't register and <knowledge_tools> never appears.
knowledge:
  enabled: $(bool $PROXY_ENABLE_TDAI)
  endpoint: "http://memory-core:8420"
  serviceToken: "${MEMORY_CORE_GATEWAY_API_KEY}"
  serviceId: default

auth:
  enabled: $(bool $PROXY_ENABLE_AUTH)
  url: "http://memory-core:8420"
  timeoutMs: 5000

sessionInit:
  enabled: $(bool $PROXY_ENABLE_SESSION_INIT)
  maxRetries: 3
  injectAgentContext: true
  injectTaskContext: true
  headerAutoSelect:
    enabled: true
    teamHeader: "x-team-id"
    agentHeader: "x-agent-id"
    taskHeader: "x-task-id"
    onMismatch: "form"

costGuard:
  enabled: false

# Turn on the skill + knowledge + tdai-memory injectors;
# knowledge needs memory-hub to be up, otherwise the hook degrades to an empty block.
injection:
  enabled: true
  injectors:
    - skill
    - knowledge
    - tdai-memory

redis:
  enabled: false
YAML

info "Starting proxy (image=$PROXY_IMAGE, port=$PROXY_PORT)"
$DOCKER run -d --name "$CONTAINER" \
  --network "$NETWORK" \
  --network-alias proxy \
  --add-host=host.docker.internal:host-gateway \
  -p "${PROXY_PORT}:8096" \
  -v "$CONFIG_FILE:/data/config.yaml:ro" \
  "$PROXY_IMAGE" >/dev/null

wait_healthy "$CONTAINER" 90
ok "proxy started → http://localhost:${PROXY_PORT}/"
ok "  Usage: point your coding agent's API base at http://localhost:${PROXY_PORT}"
